[build] fix "changes meaning" compiler error under WSL
```
compiling  run_model_simple.cc :

    In file included from /home/dkp/LiteRT/litert/cc/litert_compiled_model.h:38,
                     from /home/dkp/LiteRT/cmake_example/run_model_simple.cc:29:
    /home/dkp/LiteRT/litert/cc/litert_buffer_ref.h:148:21: error: declaration of ‘litert::Span<const T>
  litert::BufferRef<ByteT>::Span() const’ changes meaning of ‘Span’ [-Wchanges-meaning]
      148 |   Span<const ByteT> Span() const {
          |                     ^~~~
    /home/dkp/LiteRT/litert/cc/litert_buffer_ref.h:148:3: note: used here to mean ‘using litert::Span =
  class absl::lts_20260107::Span<const T>’
      148 |   Span<const ByteT> Span() const {
          |   ^~~~~~~~~~~~~~~~~
```

Instead of adding `-fpermissive` to `run_model_simple`, this commit updates
the SDK files to make it standard-compliant (which is also suggested by Gemini).